FROM docker.io/postgres:13.18-alpine3.21

RUN set -eux; \
    apk update; \
    apk add musl-locales; \
    apk add postgresql17;

ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres
ENV POSTGRES_PASSWORD=""
ENV POSTGRES_HOST_AUTH_METHOD=md5
ENV EXTENSIONS=""

ENV PGBINOLD /usr/local/bin/
ENV PGBINNEW /usr/libexec/postgresql17/

ENV PGDATAOLD /var/lib/postgresql/data
ENV PGDATANEW /var/lib/postgresql/17/data

RUN set -eux; \
	mkdir -p "${PGDATAOLD}" "${PGDATANEW}"; \
	chown -R postgres:postgres /var/lib/postgresql

WORKDIR /var/lib/postgresql

COPY docker-upgrade /usr/local/bin/

ENTRYPOINT ["docker-upgrade"]

CMD ["pg_upgrade", "-U", "${POSTGRES_USER}" ]
