FROM docker.io/library/postgres:17-bookworm

RUN sed -i 's/$/ 13/' /etc/apt/sources.list.d/pgdg.list

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		postgresql-13='13.18-1.pgdg120+1' \
	; \
	rm -rf /var/lib/apt/lists/*

ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres
ENV POSTGRES_PASSWORD=""
ENV POSTGRES_HOST_AUTH_METHOD=scram-sha-256
ENV EXTENSIONS=""

ENV PGBINOLD /usr/local/bin
ENV PGBINNEW /usr/local/bin

ENV PGDATAOLD /var/lib/postgresql/16/data
ENV PGDATANEW /var/lib/postgresql/17/data

RUN set -eux; \
	mkdir -p "${PGDATAOLD}" "${PGDATANEW}"; \
	chown -R postgres:postgres /var/lib/postgresql

WORKDIR /var/lib/postgresql

COPY docker-upgrade /usr/local/bin/

ENTRYPOINT ["docker-upgrade"]

CMD ["pg_upgrade", "-U", "${POSTGRES_USER}" ]
